#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t pvparameters \
                         -C "start_jupyter -T @tool -t PVparameters.ipynb" \
                         -u anaconda-6 \
                         -r none \
                         -w headless
